# Generated by Django 6.0 on 2025-12-12 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('bus_stop_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=200)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(max_length=50)),
                ('route_long_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=200)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(db_index=True, max_length=50)),
                ('shape_pt_lat', models.FloatField()),
                ('shape_pt_lon', models.FloatField()),
                ('shape_pt_sequence', models.IntegerField()),
            ],
            options={
                'ordering': ['shape_pt_sequence'],
                'indexes': [models.Index(fields=['shape_id', 'shape_pt_sequence'], name='app_shape_shape_i_a27160_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=50)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.route')),
                ('shape_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shape')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.IntegerField(db_index=True)),
                ('arrival_time', models.CharField(max_length=20)),
                ('departure_time', models.CharField(max_length=20)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trip')),
            ],
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route'], name='app_trip_route_i_1f2da3_idx'),
        ),
        migrations.AddIndex(
            model_name='stoptime',
            index=models.Index(fields=['trip', 'stop_sequence'], name='app_stoptim_trip_id_d74261_idx'),
        ),
        migrations.AddIndex(
            model_name='stoptime',
            index=models.Index(fields=['departure_time'], name='app_stoptim_departu_d021cb_idx'),
        ),
    ]
