# Generated by Django 6.0 on 2025-12-29 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('bus_stop_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=200)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(max_length=50)),
                ('route_long_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ODPassengerFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=20)),
                ('origin_station', models.CharField(db_index=True, max_length=200)),
                ('destination_station', models.CharField(db_index=True, max_length=200)),
                ('passengers', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['month'], name='app_odpasse_month_dc9a41_idx'), models.Index(fields=['origin_station'], name='app_odpasse_origin__22a3f0_idx'), models.Index(fields=['destination_station'], name='app_odpasse_destina_14134e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PassengerFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=20)),
                ('businessday', models.DateField(db_index=True)),
                ('linename', models.CharField(max_length=20)),
                ('sitename', models.CharField(max_length=200)),
                ('station_name', models.CharField(db_index=True, max_length=200)),
                ('station_code', models.CharField(max_length=20)),
                ('hour', models.IntegerField(db_index=True)),
                ('entry', models.IntegerField(default=0)),
                ('exit', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['month', 'station_name'], name='app_passeng_month_b7aee0_idx'), models.Index(fields=['station_name', 'hour'], name='app_passeng_station_146046_idx')],
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(db_index=True, max_length=50)),
                ('shape_pt_lat', models.FloatField()),
                ('shape_pt_lon', models.FloatField()),
                ('shape_pt_sequence', models.IntegerField()),
            ],
            options={
                'ordering': ['shape_pt_sequence'],
                'indexes': [models.Index(fields=['shape_id', 'shape_pt_sequence'], name='app_shape_shape_i_a27160_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stop_id', models.CharField(db_index=True, max_length=20)),
                ('station_code', models.CharField(db_index=True, max_length=20)),
                ('stop_name', models.CharField(db_index=True, max_length=200)),
                ('line', models.CharField(db_index=True, max_length=50)),
                ('interchange', models.BooleanField(default=False)),
                ('interchange_between', models.CharField(blank=True, help_text='Comma separated lines e.g. Blue,Yellow', max_length=100, null=True)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('line_color', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['stop_id'], name='app_stops_stop_id_82cf6e_idx'), models.Index(fields=['stop_name'], name='app_stops_stop_na_6a3546_idx'), models.Index(fields=['station_code'], name='app_stops_station_1402dd_idx'), models.Index(fields=['line'], name='app_stops_line_176c87_idx'), models.Index(fields=['interchange'], name='app_stops_interch_e14e75_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=50)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.route')),
                ('shape_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shape')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.IntegerField(db_index=True)),
                ('arrival_time', models.CharField(max_length=20)),
                ('departure_time', models.CharField(max_length=20)),
                ('stops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stops')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trip')),
            ],
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route'], name='app_trip_route_i_1f2da3_idx'),
        ),
        migrations.AddIndex(
            model_name='stoptime',
            index=models.Index(fields=['trip', 'stop_sequence'], name='app_stoptim_trip_id_d74261_idx'),
        ),
        migrations.AddIndex(
            model_name='stoptime',
            index=models.Index(fields=['departure_time'], name='app_stoptim_departu_d021cb_idx'),
        ),
    ]
