# Generated by Django 6.0 on 2025-12-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=20)),
                ('businessday', models.DateField(db_index=True)),
                ('linename', models.CharField(max_length=20)),
                ('sitename', models.CharField(max_length=200)),
                ('station_name', models.CharField(db_index=True, max_length=200)),
                ('station_code', models.CharField(max_length=20)),
                ('hour', models.IntegerField(db_index=True)),
                ('entry', models.IntegerField(default=0)),
                ('exit', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['month', 'station_name'], name='app_passeng_month_b7aee0_idx'), models.Index(fields=['station_name', 'hour'], name='app_passeng_station_146046_idx')],
            },
        ),
    ]
